name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check for core files
        run: |
          if [ ! -f "index.html" ]; then
            echo "Error: index.html is missing!"
            exit 1
          fi
          echo "Build successful: index.html is present!"